dairyProducts = ['牛乳', '卵', 'チーズ']
meat = ['鶏', '豚', '牛', 'ししゃも']
snack = ['クッキー', 'パイ', '揚げせん', 'チョコ', 'アーモンド', 'ケーキ', 'フルグラ', 'コーンフレーク', 'ポテト']
staple = ['パン', 'ブレッド', 'うどん', 'ご飯', 'パスタ', '餅']
drink = ['珈琲', '緑茶']
vegetable = ['じゃがいも', 'レタス', '水菜', '舞茸', '榎茸', '小松菜', 'ほうれん草', '野菜', 'ブロッコリー', '人参', 'ピーマン', 'きゅうり', 'トマト', '白菜', '大根', '壬生菜', 'パプリカ', 'ぶなしめじ', 'グリーンオーク', 'キャベツ']
processed_goods = ['ちくわ', '納豆', '西京漬', '厚揚げ', 'かに風', 'ウインナー', '油揚げ']
Souzai = ['アジフライ']
Touhu = ['豆腐']
Flutu = ['バナナ', '西京漬', '果物', 'りんご', 'みかん']
seasoning = ['三温糖']
dessert = ['プリン']
itemDB = {'乳製品': dairyProducts, '肉類': meat, 'お菓子': snack, '主食': staple, '飲み物': drink, '野菜': vegetable, '加工品': processed_goods, '惣菜': Souzai, '豆腐': Touhu, '果物': Flutu, '調味料': seasoning, 'デザート': dessert}
categoryDB = {'乳製品': 'dairyProducts', '肉類': 'meat', 'お菓子': 'snack', '主食': 'staple', '飲み物': 'drink', '野菜': 'vegetable', '加工品': 'processed_goods', '惣菜': 'Souzai', '豆腐': 'Touhu', '果物': 'Flutu', '調味料': 'seasoning', 'デザート': 'dessert'}
