dairyProducts = ['牛乳', '卵', 'チーズ', 'newItem']
meat = ['鶏', '豚', '牛', 'ししゃも']
snack = ['クッキー', 'パイ', '揚げせん', 'チョコ', 'アーモンド', 'ケーキ', 'フルグラ', 'コーンフレーク', 'ポテト']
staple = ['パン', 'ブレッド', 'うどん', 'ご飯', 'パスタ']
drink = ['珈琲', '緑茶']
vegetable = ['じゃがいも', 'レタス', '水菜', '舞茸', '榎茸', '小松菜', 'ほうれん草', '野菜', 'ブロッコリー', '人参', 'ピーマン', 'きゅうり']
processed_goods = ['ちくわ', '納豆', '西京漬', '厚揚げ', 'かに風', 'ウインナー']
newcategory = ['newItem', 'newI', 'newItem2']
itemDB = {'乳製品': dairyProducts, '肉類': meat, 'お菓子': snack, '主食': staple, '飲み物': drink, '野菜': vegetable, '加工品': processed_goods, '新しい': newcategory}
categoryDB = {'乳製品': 'dairyProducts', '肉類': 'meat', 'お菓子': 'snack', '主食': 'staple', '飲み物': 'drink', '野菜': 'vegetable', '加工品': 'processed_goods', '新しい': 'newcategory'}
